### ISSUE TITLE
Build with ghc-9.2.1

### ISSUE THREAD

**Issue by andremarianiello** [nikita-volkov/hasql-th#22]
Due to some changes in the `template-haskell` package, `hasql-th` does not build with ghc-9.2.1.

```
library/Hasql/TH/Construction/Exp.hs:85:19: error:
    • Couldn't match expected type: TyVarBndr Specificity
                  with actual type: flag0 -> TyVarBndr flag0
    • Probable cause: ‘PlainTV’ is applied to too few arguments
      In the expression: PlainTV _fName
      In the first argument of ‘ForallT’, namely ‘[PlainTV _fName]’
      In the expression:
        ForallT
          [PlainTV _fName] [AppT (ConT ''Divisible) (VarT _fName)]
          (AppT (VarT _fName) (TupleT 0))
   |
85 |       in ForallT [PlainTV _fName] [AppT (ConT ''Divisible) (VarT _fName)]
   |                   ^^^^^^^^^^^^^^

library/Hasql/TH/Construction/Exp.hs:121:9: error:
    • Couldn't match expected type ‘Pat’
                  with actual type ‘[Pat] -> Pat’
    • Probable cause: ‘ConP’ is applied to too few arguments
      In the expression:
        ConP
          'Fold [VarP _stepVarName, VarP _initVarName, VarP _extractVarName]
      In the first argument of ‘LamE’, namely
        ‘[ConP 'Fold [VarP _stepVarName, VarP _initVarName, ....]]’
      In the expression:
        LamE
          [ConP 'Fold [VarP _stepVarName, VarP _initVarName, ....]]
          (_body
             (VarE _stepVarName) (VarE _initVarName) (VarE _extractVarName))
    |
121 |         ConP 'Fold
    |         ^^^^^^^^^^...

library/Hasql/TH/Construction/Exp.hs:123:13: error:
    • Couldn't match expected type ‘Type’ with actual type ‘Pat’
    • In the expression: VarP _stepVarName
      In the second argument of ‘ConP’, namely
        ‘[VarP _stepVarName, VarP _initVarName, VarP _extractVarName]’
      In the expression:
        ConP
          'Fold [VarP _stepVarName, VarP _initVarName, VarP _extractVarName]
    |
123 |             VarP _stepVarName,
    |             ^^^^^^^^^^^^^^^^^
    
library/Hasql/TH/Construction/Exp.hs:124:13: error:
    • Couldn't match expected type ‘Type’ with actual type ‘Pat’
    • In the expression: VarP _initVarName
      In the second argument of ‘ConP’, namely
        ‘[VarP _stepVarName, VarP _initVarName, VarP _extractVarName]’
      In the expression:
        ConP
          'Fold [VarP _stepVarName, VarP _initVarName, VarP _extractVarName]
    |
124 |             VarP _initVarName,
    |             ^^^^^^^^^^^^^^^^^

library/Hasql/TH/Construction/Exp.hs:125:13: error:
    • Couldn't match expected type ‘Type’ with actual type ‘Pat’
    • In the expression: VarP _extractVarName
      In the second argument of ‘ConP’, namely
        ‘[VarP _stepVarName, VarP _initVarName, VarP _extractVarName]’
      In the expression:
        ConP
          'Fold [VarP _stepVarName, VarP _initVarName, VarP _extractVarName]
    |
125 |             VarP _extractVarName
    |             ^^^^^^^^^^^^^^^^^^^^
```

I was going to try fixing them myself, and then I noticed a dep `template-haskell-compat-v0208` which I assume was created to keep this package working with older version of `template-haskell`, so I decided to file this instead of just going in an updating stuff that changed.

**Comment by nikita-volkov** [comment]
Thanks for the report. I'll look into it

**Comment by nikita-volkov** [comment]
Fixed and released

**Comment by torgeirsh** [comment]
Thanks! I had the same problem in GHC 9.0.2, and the fix works for that as well.
